name = piemart
description = PieMart - A full-featured player market system with currency, exchange, and hosted markets.
depends = default
optional_depends = sfinv, unified_inventory
author = Endvoxel ( aa1a )
